import {test,expect} from '@playwright/test'
test('Stripe checkout shows recurring authorisation and sends the selected three-month package',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('offscroll-times-envelope-seen-v1','1'))
  await page.route('**/api/session',route=>route.fulfill({json:{csrf:'stripe-csrf'}}))
  await page.goto('/checkout/stripe?duration=3&quantity=1&country=IN')
  await expect(page.getByText(/Then.*every 3 months until cancelled/)).toBeVisible()
  await page.getByPlaceholder('Full name',{exact:true}).fill('Test Reader')
  await page.getByPlaceholder('Email',{exact:true}).fill('reader@example.com')
  await page.getByPlaceholder('Phone number',{exact:true}).fill('+919999999999')
  await page.getByPlaceholder('Address line 1',{exact:true}).fill('1 Test Road')
  await page.getByPlaceholder('City / town',{exact:true}).fill('Pune')
  await page.getByPlaceholder('State / region',{exact:true}).fill('Maharashtra')
  await page.getByPlaceholder('PIN code',{exact:true}).fill('411001')
  await page.getByRole('checkbox').first().check()
  await page.route('**/api/stripe/checkout',route=>route.fulfill({status:503,json:{error:'Stripe test configuration needed.'}}))
  const submitted=page.waitForRequest(request=>request.url().endsWith('/api/stripe/checkout'))
  await page.getByRole('button',{name:'Continue to Stripe'}).click()
  expect((await submitted).postDataJSON()).toMatchObject({durationMonths:3,quantity:1,acceptTerms:true,csrf:'stripe-csrf'})
  await expect(page.getByRole('alert').filter({hasText:'Stripe test configuration needed.'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Return and retry safely'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
