import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { SiteHeader } from '#/components/SiteHeader'
import { SiteFooter } from '#/components/Faq'
import { CTA, CTA_OUTLINE, EYEBROW, H2 } from '#/lib/uiKit'
import { AdminFileLibrary } from '#/components/AdminFileLibrary'

type Row = Record<string, any>
type AdminData = {
  user: { id: string; name?: string }; csrf: string
  subscriptions: Row[]; payments: Row[]; fulfilments: Row[]; editions: Row[]; eligibility: Row[]
  products: Row[]; options: Row[]; discounts: Row[]; zones: Row[]; content: Row[]; enquiries: Row[]; audits: Row[]; promotionReports: Row[]
  reports: {
    customers: number; activeSubscriptions: number; activePaidEntitlements: number; entitledCopiesRemaining: number; upcomingExpirations: number; cancellations: number; completedTerms: number; renewals: number; retentionPercent: number
    addressExceptions: number; paymentExceptions: number; fulfilmentExceptions: number; deliveryExceptions: number
    paidRevenueMinor: number; refundedPayments: number; refundedMinor: number; discountRedemptions: number; discountCostMinor: number
    nextEdition: { label: string; dispatchAt: number; copiesRequired: number; eligibilityGenerated: boolean } | null
    countryDistribution: Array<{ country: string; subscriptions: number; copies: number }>
    fulfilmentByCountry: Array<{ country: string; required: number; dispatched: number }>
    funnel: { pageViews:number; durationSelections:number; checkoutStarts:number; successfulPurchases:number; paymentFailures:number }
  }
}

export const Route = createFileRoute('/admin')({
  head: () => ({ meta: [{ title: 'Administrator | Offscroll Times' }, { name: 'robots', content: 'noindex, nofollow' }] }),
  component: AdminPage,
})

const input = 'w-full rounded-xl border border-graphite bg-white px-3 py-2 text-sm'
const card = 'rounded-2xl border border-graphite bg-paper p-5'

function AdminPage() {
  const [data, setData] = useState<AdminData | null>(null)
  const [state, setState] = useState<'loading'|'denied'|'ready'|'error'>('loading')
  const [error, setError] = useState('')
  const [tab, setTab] = useState('overview')
  const [busy, setBusy] = useState(false)

  async function load() {
    const response = await fetch('/api/admin', { headers: { Accept: 'application/json' } })
    if (response.status === 403) { setState('denied'); return }
    const result = await response.json() as AdminData & { error?: string }
    if (!response.ok) { setError(result.error ?? 'Admin data could not be loaded.'); setState('error'); return }
    setData(result); setState('ready')
  }
  useEffect(() => { void load() }, [])

  async function mutate(payload: Record<string, unknown>) {
    if (!data || busy) return false
    setBusy(true); setError('')
    const response = await fetch('/api/admin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ csrf: data.csrf, ...payload }) })
    const result = await response.json() as { error?: string }
    if (!response.ok) { setError(result.error ?? 'Update failed.'); setBusy(false); return false }
    await load(); setBusy(false); return true
  }

  return <><SiteHeader /><main className="mx-auto min-h-[70vh] max-w-[1400px] px-4 py-12 sm:px-6 lg:px-10">
    {state === 'loading' && <p className={EYEBROW}>Checking administrator access…</p>}
    {state === 'denied' && <section className={`${card} mx-auto max-w-xl text-center`}><p className={EYEBROW}>Restricted area</p><h1 className={`${H2} mt-3`}>Administrator access required.</h1><p className="mt-4 text-graphite-soft">Sign in with an explicitly approved Google or Microsoft identity. Customer accounts cannot access this dashboard.</p><a className={`${CTA} mt-6`} href="/login?returnTo=/admin">Administrator sign in</a><a className={`${CTA_OUTLINE} ml-3 mt-6`} href="/">Return home</a></section>}
    {error && <p role="alert" className="mb-6 rounded-xl border border-red-700 bg-red-50 p-4 text-red-900">{error}</p>}
    {data && <>
      <header className="flex flex-wrap items-end justify-between gap-5 border-b border-graphite pb-7"><div><p className={EYEBROW}>Administrator</p><h1 className="m-0 font-display text-5xl font-bold tracking-tight">Business control room</h1><p className="mt-3 text-graphite-soft">Signed in as {data.user.name ?? data.user.id}</p></div><a className={CTA_OUTLINE} href="/account">Customer view</a></header>
      <nav className="my-7 flex flex-wrap gap-2" aria-label="Admin sections">{['overview','subscriptions','editions','enquiries','catalogue','files','content','audit'].map(item => <button key={item} onClick={() => setTab(item)} className={`rounded-full border border-graphite px-4 py-2 font-mono text-xs uppercase ${tab === item ? 'bg-graphite text-paper' : 'bg-paper'}`}>{item}</button>)}</nav>
      {tab === 'overview' && <Overview data={data} />}
      {tab === 'subscriptions' && <Subscriptions data={data} busy={busy} mutate={mutate} />}
      {tab === 'editions' && <Editions data={data} busy={busy} mutate={mutate} />}
      {tab === 'enquiries' && <Enquiries rows={data.enquiries} busy={busy} mutate={mutate} />}
      {tab === 'catalogue' && <Catalogue data={data} busy={busy} mutate={mutate} />}
      {tab === 'files' && <AdminFileLibrary csrf={data.csrf} />}
      {tab === 'content' && <Content data={data} busy={busy} mutate={mutate} />}
      {tab === 'audit' && <Audit rows={data.audits} />}
    </>}
  </main><SiteFooter /></>
}

function Enquiries({ rows, busy, mutate }: { rows: Row[]; busy: boolean; mutate: (p: Record<string,unknown>) => Promise<boolean> }) {
  return <section><h2 className={H2}>Contact enquiries</h2><div className="mt-6 grid gap-4">{rows.length === 0 && <p>No enquiries yet.</p>}{rows.map(row => <article className={card} key={row.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="m-0 font-mono text-xs font-bold uppercase">{row.reference} · {row.enquiry_type}</p><h3 className="mt-2 text-xl font-bold">{row.name}</h3><a href={`mailto:${row.email}`}>{row.email}</a>{row.country && <span> · {row.country}</span>}</div><select disabled={busy} value={row.status} className={`${input} w-auto`} onChange={event=>void mutate({action:'enquiry.update',enquiryId:row.id,status:event.target.value,staffNotes:row.staff_notes})}>{['new','in_progress','waiting_customer','resolved','closed'].map(status=><option key={status}>{status}</option>)}</select></div>{row.detail && <p className="mt-3 text-sm"><strong>Detail:</strong> {row.detail}</p>}<p className="mt-3 whitespace-pre-wrap text-sm">{row.message}</p><label className="mt-4 block text-sm font-bold">Private staff notes<textarea defaultValue={row.staff_notes} className={`${input} mt-1 min-h-24`} onBlur={event=>void mutate({action:'enquiry.update',enquiryId:row.id,status:row.status,staffNotes:event.target.value})}/></label></article>)}</div></section>
}

function Overview({ data }: { data: AdminData }) {
  const money = (minor: number) => new Intl.NumberFormat('en', { style:'currency', currency:'USD' }).format(minor / 100)
  const statusStats = [['Paid entitlements',data.reports.activePaidEntitlements],['Copies remaining',data.reports.entitledCopiesRemaining],['Cancelled',data.reports.cancellations],['Completed terms',data.reports.completedTerms]]
  const exceptions = [['Payment',data.reports.paymentExceptions],['Address',data.reports.addressExceptions],['Fulfilment',data.reports.fulfilmentExceptions],['Delivery',data.reports.deliveryExceptions]]
  const commercial = [['Revenue',money(data.reports.paidRevenueMinor)],['Refunds',`${data.reports.refundedPayments} · ${money(data.reports.refundedMinor)}`],['Discount uses',data.reports.discountRedemptions],['Discount cost',money(data.reports.discountCostMinor)]]
  return <div className="grid gap-7">
    <section><div className="flex items-end justify-between gap-4"><div><p className={EYEBROW}>Subscription health</p><h2 className="text-2xl font-bold">Customer terms</h2></div><p className="font-mono text-xs uppercase">{data.reports.customers} customers</p></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{statusStats.map(([label,value]) => <Metric key={String(label)} label={String(label)} value={value} />)}</div></section>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_2fr]">
      <article className="rounded-2xl border border-graphite bg-sun p-6"><p className={EYEBROW}>Next edition</p>{data.reports.nextEdition ? <><h2 className="mt-2 text-3xl font-bold">{data.reports.nextEdition.label}</h2><strong className="mt-6 block text-5xl">{data.reports.nextEdition.copiesRequired}</strong><p className="mt-1">copies currently required</p><p className="mt-5 text-sm">Dispatch: {new Date(data.reports.nextEdition.dispatchAt).toLocaleDateString()}</p>{!data.reports.nextEdition.eligibilityGenerated && <p className="mt-3 rounded-lg border border-graphite bg-paper/70 p-3 text-sm">Generate the edition eligibility list to calculate its print quantity.</p>}</> : <><h2 className="mt-2 text-3xl font-bold">No edition scheduled</h2><p className="mt-4">Create the next edition to prepare its dispatch list.</p></>}</article>
      <div><p className={EYEBROW}>Needs attention</p><h2 className="text-2xl font-bold">Operational exceptions</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{exceptions.map(([label,value]) => <Metric key={String(label)} label={`${label} exceptions`} value={value} alert={Number(value) > 0} />)}</div></div>
    </section>
    <section><p className={EYEBROW}>Commercial summary</p><h2 className="text-2xl font-bold">Revenue, refunds and promotions</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{commercial.map(([label,value]) => <Metric key={String(label)} label={String(label)} value={value} />)}</div></section>
    <section><p className={EYEBROW}>First-party funnel</p><h2 className="text-2xl font-bold">Anonymous consented activity</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(data.reports.funnel).map(([label,value])=><Metric key={label} label={label.replace(/([A-Z])/g,' $1')} value={value}/>)}</div></section>
    <section><p className={EYEBROW}>Lifecycle</p><h2 className="text-2xl font-bold">Completion and retention</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Renewals" value={data.reports.renewals}/><Metric label="Retention" value={`${data.reports.retentionPercent}%`}/><Metric label="Refunds" value={data.reports.refundedPayments}/></div></section>
    <section className={card}><p className={EYEBROW}>Delivery footprint</p><h2 className="text-2xl font-bold">Country distribution</h2>{data.reports.countryDistribution.length ? <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-graphite"><th className="py-3">Country</th><th>Subscriptions</th><th>Monthly copies</th></tr></thead><tbody>{data.reports.countryDistribution.map(row => <tr className="border-b border-rule last:border-0" key={row.country}><th className="py-3">{row.country}</th><td>{row.subscriptions}</td><td>{row.copies}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-graphite-soft">Country data will appear after customers add delivery addresses.</p>}</section>
    <section className={card}><p className={EYEBROW}>Fulfilment by country</p><h2 className="text-2xl font-bold">Required and dispatched copies</h2><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Country</th><th>Required</th><th>Dispatched</th></tr></thead><tbody>{data.reports.fulfilmentByCountry.map(row=><tr className="border-t border-rule" key={row.country}><th className="py-3">{row.country}</th><td>{row.required}</td><td>{row.dispatched}</td></tr>)}</tbody></table></div></section>
  </div>
}

function Metric({ label, value, alert = false }: { label: string; value: React.ReactNode; alert?: boolean }) {
  return <article className={`${card} ${alert ? 'border-red-700 bg-red-50' : ''}`}><p className="font-mono text-xs uppercase text-graphite-soft">{label}</p><strong className="mt-3 block text-3xl">{value}</strong></article>
}

function Subscriptions({ data, busy, mutate }: { data: AdminData; busy: boolean; mutate: (p: Record<string,unknown>) => Promise<boolean> }) {
  const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[country,setCountry]=useState('all'),[duration,setDuration]=useState('all')
  const availableCountries=Array.from(new Set(data.subscriptions.map(row=>row.delivery_address?.country).filter(Boolean))).sort()
  const rows=data.subscriptions.filter(row=>{const haystack=`${row.customer_id} ${row.contact_email??''} ${row.contact_phone??''} ${row.delivery_address?.name??''}`.toLowerCase();return haystack.includes(query.toLowerCase())&&(status==='all'||row.status===status)&&(country==='all'||row.delivery_address?.country===country)&&(duration==='all'||String(row.duration_months)===duration)})
  const transitions:Record<string,string[]>={upcoming:['active','paused','cancelled'],active:['paused','cancelled','completed'],paused:['active','cancelled','completed'],cancelled:['active','completed'],payment_failed:['upcoming','cancelled']}
  const date=(value:unknown)=>value?new Date(Number(value)).toLocaleDateString():'—'
  function correctAddress(row: Row) { const old=row.delivery_address??{}; const name=window.prompt('Recipient name',old.name??''); if(!name)return; const line1=window.prompt('Address line 1',old.line1??''); if(!line1)return; const city=window.prompt('City',old.city??''); if(!city)return; const postalCode=window.prompt('Postal code',old.postalCode??''); if(!postalCode)return; const countryCode=window.prompt('Two-letter country code',old.country??'IN'); if(!countryCode)return; const reason=window.prompt('Reason for this correction (required)'); if(!reason||reason.trim().length<5)return; if(!window.confirm(`Save this address correction for ${row.contact_email??row.customer_id}? The previous and new addresses will be audited.`))return; void mutate({action:'subscription.address',subscriptionId:row.id,reason,address:{name,line1,line2:old.line2,city,region:old.region,postalCode,country:countryCode}}) }
  function changeStatus(row:Row,next:string){const reason=window.prompt(`Reason for changing ${row.status} to ${next} (required)`);if(!reason||reason.trim().length<5)return;if(!window.confirm(`Confirm ${next} for ${row.contact_email??row.customer_id}. This action is recorded in the audit trail.`))return;void mutate({action:'subscription.status',subscriptionId:row.id,status:next,reason})}
  function refund(_payment?:Row,_row?:Row){window.alert('Create and approve the refund in Razorpay. Offscroll Times records it only after receiving a signed Razorpay refund webhook.')}
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className={H2}>Customers and subscriptions</h2><p className="mt-2 text-sm text-graphite-soft">Search records, inspect paid entitlement and fulfilment history, or apply audited corrections.</p></div><p className="font-mono text-xs uppercase">{rows.length} of {data.subscriptions.length} records</p></div>
    <div className={`${card} mt-6 grid gap-3 md:grid-cols-4`} aria-label="Subscription filters"><label className="text-sm font-bold">Customer, email or phone<input className={`${input} mt-1`} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></label><label className="text-sm font-bold">Status<select className={`${input} mt-1`} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['upcoming','active','paused','cancelled','completed','refunded','payment_failed'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-bold">Country<select className={`${input} mt-1`} value={country} onChange={e=>setCountry(e.target.value)}><option value="all">All countries</option>{availableCountries.map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-bold">Plan duration<select className={`${input} mt-1`} value={duration} onChange={e=>setDuration(e.target.value)}><option value="all">All durations</option>{Array.from(new Set(data.subscriptions.map(row=>row.duration_months))).sort((a,b)=>a-b).map(v=><option key={v} value={v}>{v} months</option>)}</select></label></div>
    <div className="mt-6 grid gap-4">{rows.length===0&&<p className={card}>No subscriptions match these filters.</p>}{rows.map(row=>{const payments=data.payments.filter(p=>p.subscription_id===row.id),history=data.fulfilments.filter(f=>f.subscription_id===row.id),audits=data.audits.filter(a=>a.target_type==='subscription'&&a.target_id===row.id);return <article className={card} key={row.id}><div className="grid gap-5 lg:grid-cols-[1.2fr_1fr_1fr_auto]"><div><p className="font-mono text-xs uppercase">{row.customer_id}</p><h3 className="mt-2 text-xl font-bold">{row.contact_email||'Email pending'}</h3><p className="mt-1 text-sm">{row.contact_phone||'Phone not recorded'} · {row.delivery_address?`${row.delivery_address.city}, ${row.delivery_address.country}`:'Address missing'}</p></div><dl className="grid grid-cols-2 gap-2 text-sm"><div><dt className="text-graphite-soft">Status</dt><dd className="font-bold capitalize">{row.status}</dd></div><div><dt className="text-graphite-soft">Entitlement</dt><dd className="font-bold capitalize">{row.entitlement_status||'pending'}</dd></div><div><dt className="text-graphite-soft">Starts</dt><dd>{date(row.starts_at)}</dd></div><div><dt className="text-graphite-soft">Paid through</dt><dd>{date(row.paid_through_at||row.ends_at)}</dd></div></dl><div><p className="text-sm text-graphite-soft">{row.plan_name} · {row.duration_months} months</p><strong className="mt-2 block text-2xl">{Math.max(0,row.copies_total-row.copies_fulfilled)} remaining</strong><p className="text-sm">{row.copies_fulfilled} fulfilled of {row.copies_total}</p></div><div className="flex flex-wrap items-start gap-2"><button disabled={busy} className={CTA_OUTLINE} onClick={()=>correctAddress(row)}>Correct address</button>{transitions[row.status]?.map(next=><button disabled={busy} className={CTA_OUTLINE} key={next} onClick={()=>changeStatus(row,next)}>{next}</button>)}</div></div>
      <details className="mt-5 border-t border-rule pt-4"><summary className="cursor-pointer font-bold">Pricing, payments, fulfilment and audit history</summary><div className="mt-4 grid gap-5 lg:grid-cols-4"><section><h4 className="font-mono text-xs font-bold uppercase">Purchase pricing</h4>{row.pricing_snapshot?<dl className="mt-2 grid grid-cols-2 gap-1 text-sm"><dt>Subtotal</dt><dd>{row.currency} {(Number(row.pricing_snapshot.subtotalMinor??0)/100).toFixed(2)}</dd><dt>Discounts</dt><dd>-{row.currency} {((Number(row.pricing_snapshot.durationDiscountMinor??0)+Number(row.pricing_snapshot.offerDiscountMinor??0))/100).toFixed(2)}</dd><dt>Shipping</dt><dd>{row.currency} {(Number(row.pricing_snapshot.shippingMinor??0)/100).toFixed(2)}</dd><dt>Tax</dt><dd>{row.currency} {(Number(row.pricing_snapshot.taxMinor??0)/100).toFixed(2)}</dd><dt className="font-bold">Total</dt><dd className="font-bold">{row.currency} {(Number(row.pricing_snapshot.totalMinor??row.amount_minor)/100).toFixed(2)}</dd></dl>:<p className="mt-2 text-sm">Legacy pricing snapshot unavailable.</p>}</section><section><h4 className="font-mono text-xs font-bold uppercase">Payments</h4>{payments.length?payments.map(payment=><div className="mt-2 text-sm" key={payment.id}><span className="capitalize">{payment.status}</span> · {payment.currency} {(payment.amount_minor/100).toFixed(2)} · {date(payment.paid_at||payment.created_at)}{payment.status==='paid'&&<button className="ml-2 underline" onClick={()=>refund(payment,row)}>Refund instructions</button>}</div>):<p className="mt-2 text-sm">No payment record.</p>}</section><section><h4 className="font-mono text-xs font-bold uppercase">Fulfilment</h4>{history.length?history.map(item=><p className="mt-2 text-sm" key={item.id}>{item.edition_label} · <span className="capitalize">{item.status}</span> · {date(item.dispatched_at||item.created_at)}</p>):<p className="mt-2 text-sm">No editions assigned.</p>}</section><section><h4 className="font-mono text-xs font-bold uppercase">Audit trail</h4>{audits.length?audits.map(item=><p className="mt-2 text-sm" key={item.id}>{item.action} · {date(item.created_at)} · {item.actor_user_id}</p>):<p className="mt-2 text-sm">No administrative changes.</p>}</section></div></details></article>})}</div></section>
}

function Editions({ data, busy, mutate }: { data: AdminData; busy: boolean; mutate: (p: Record<string,unknown>) => Promise<boolean> }) {
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); if (await mutate({action:'edition.create',label:f.get('label'),issueNumber:Number(f.get('issue')),cutoff:f.get('cutoff'),dispatch:f.get('dispatch')})) event.currentTarget.reset() }
  return <EditionManager data={data} busy={busy} mutate={mutate} create={create}/>
  // Kept temporarily as a compact fallback while the richer manager remains API-compatible.
  return <div className="grid gap-7 lg:grid-cols-[360px_1fr]"><form className={card} onSubmit={create}><h2 className="text-2xl font-bold">Create edition</h2>{[['label','Edition label','text'],['issue','Issue number','number'],['cutoff','Eligibility cut-off','datetime-local'],['dispatch','Dispatch date','datetime-local']].map(([name,label,type]) => <label className="mt-4 block" key={name}><span className="mb-1 block text-sm">{label}</span><input className={input} required name={name} type={type}/></label>)}<button disabled={busy} className={`${CTA} mt-5`} type="submit">Create edition</button></form><section><h2 className={H2}>Editions and dispatch</h2><div className="mt-5 grid gap-4">{data.editions.map(e => <article className={card} key={e.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{e.label}</strong><p className="mt-1 text-sm capitalize">Issue {e.issue_number} · {e.status}</p></div><div className="flex gap-2"><button disabled={busy} className={CTA_OUTLINE} onClick={() => void mutate({action:'edition.generate',editionId:e.id})}>Generate list</button><a className={CTA_OUTLINE} href={`/api/admin/dispatch?edition=${encodeURIComponent(e.id)}`}>Export CSV</a></div></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><tbody>{data.fulfilments.filter(f => f.edition_label === e.label).map(f => <tr key={f.id}><td className="py-2">{f.subscription_id}</td><td className="py-2"><select className={input} value={f.status} onChange={event => void mutate({action:'fulfilment.status',fulfilmentId:f.id,status:event.target.value})}>{['scheduled','prepared','dispatched','delivered','delayed','returned','replacement'].map(s => <option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></article>)}</div></section></div>
}

function EditionManager({data,busy,mutate,create}:{data:AdminData;busy:boolean;mutate:(p:Record<string,unknown>)=>Promise<boolean>;create:(e:React.FormEvent<HTMLFormElement>)=>Promise<void>}){
  const next:Record<string,string[]>={scheduled:['prepared'],prepared:['dispatched'],dispatched:['delivered','delayed','returned'],delayed:['delivered','returned','replacement'],returned:['replacement'],replacement:['prepared']}
  function override(edition:Row,item:Row,include:boolean){const reason=window.prompt(`Document why this subscription should be ${include?'included':'excluded'} (required)`);if(!reason||reason.trim().length<5)return;if(!window.confirm(`Confirm this documented override for ${item.subscription_id}?`))return;void mutate({action:'edition.override',editionId:edition.id,subscriptionId:item.subscription_id,include,reason})}
  function lock(edition:Row){const reason=window.prompt('Approval note for locking this print list (required)');if(!reason||reason.trim().length<5)return;if(!window.confirm(`Lock ${edition.label}? Eligibility overrides will stop and the CSV will become available.`))return;void mutate({action:'edition.lock',editionId:edition.id,reason})}
  return <div className="grid gap-7 lg:grid-cols-[360px_1fr]"><form className={`${card} self-start lg:sticky lg:top-24`} onSubmit={e=>void create(e)}><p className={EYEBROW}>Monthly workflow</p><h2 className="text-2xl font-bold">Create edition</h2>{[['label','Edition name','text'],['issue','Issue number','number'],['cutoff','Eligibility cut-off','datetime-local'],['dispatch','Dispatch date','datetime-local']].map(([name,label,type])=><label className="mt-4 block" key={name}><span className="mb-1 block text-sm font-bold">{label}</span><input className={input} required name={name} type={type}/></label>)}<button disabled={busy} className={`${CTA} mt-5`} type="submit">Create edition</button><p className="mt-4 text-xs text-graphite-soft">Generate → review exclusions → document overrides → lock → export → fulfil.</p></form><section><h2 className={H2}>Edition and fulfilment management</h2><div className="mt-5 grid gap-5">{data.editions.length===0&&<p className={card}>No editions created yet.</p>}{data.editions.map(edition=>{const snapshots=data.eligibility.filter(item=>item.edition_id===edition.id),included=snapshots.filter(item=>['included','override_included'].includes(item.decision)),excluded=snapshots.filter(item=>['excluded','override_excluded'].includes(item.decision)),fulfilments=data.fulfilments.filter(item=>item.edition_label===edition.label),editionAudits=data.audits.filter(item=>item.target_type==='edition'&&item.target_id===edition.id),locked=['locked','dispatched','completed'].includes(edition.status);return <article className={card} key={edition.id}><header className="flex flex-wrap items-start justify-between gap-4"><div><p className={EYEBROW}>Issue {edition.issue_number} · {String(edition.status).replace('_',' ')}</p><h3 className="text-2xl font-bold">{edition.label}</h3><p className="mt-2 text-sm">Cut-off {new Date(edition.eligibility_cutoff_at).toLocaleString()} · Dispatch {new Date(edition.dispatch_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{!locked&&<button disabled={busy} className={CTA_OUTLINE} onClick={()=>void mutate({action:'edition.generate',editionId:edition.id})}>{snapshots.length?'Regenerate snapshot':'Generate snapshot'}</button>}{edition.status==='eligibility_generated'&&<button disabled={busy} className={CTA} onClick={()=>lock(edition)}>Approve & lock</button>}{locked&&<a className={CTA} href={`/api/admin/dispatch?edition=${encodeURIComponent(edition.id)}`}>Export printer CSV</a>}</div></header>{snapshots.length>0&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Included" value={included.length}/><Metric label="Excluded" value={excluded.length}/><Metric label="Print copies" value={fulfilments.filter(f=>!['returned'].includes(f.status)).reduce((sum,f)=>sum+Number(data.subscriptions.find(s=>s.id===f.subscription_id)?.quantity??1),0)}/></div>}
        {snapshots.length>0&&<details className="mt-5 border-t border-rule pt-4"><summary className="cursor-pointer font-bold">Eligibility snapshot and exclusion reasons ({snapshots.length})</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr><th className="py-2">Subscription</th><th>Decision</th><th>Reason</th><th>Review</th></tr></thead><tbody>{snapshots.map(item=><tr className="border-t border-rule" key={item.id}><td className="py-3 font-mono text-xs">{item.subscription_id}</td><td className="capitalize">{String(item.decision).replace('_',' ')}</td><td>{item.reason}</td><td>{!locked&&<button className="underline" onClick={()=>override(edition,item,!['included','override_included'].includes(item.decision))}>{['included','override_included'].includes(item.decision)?'Exclude':'Include'} with reason</button>}{locked&&<span className="text-graphite-soft">Locked</span>}</td></tr>)}</tbody></table></div></details>}
        {fulfilments.length>0&&<details className="mt-4 border-t border-rule pt-4" open={locked}><summary className="cursor-pointer font-bold">Fulfilment records ({fulfilments.length})</summary><div className="mt-3 grid gap-2">{fulfilments.map(item=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-rule p-3" key={item.id}><div><span className="font-mono text-xs">{item.subscription_id}</span><strong className="ml-3 capitalize">{item.status}</strong>{item.tracking_url&&<a className="ml-3 underline" href={item.tracking_url}>Tracking</a>}</div><div className="flex gap-2">{next[item.status]?.map(status=><button disabled={busy||!locked} className={CTA_OUTLINE} key={status} onClick={()=>{const tracking=status==='dispatched'?window.prompt('Courier tracking URL (https://, optional)')??'':'';if(window.confirm(`Confirm ${item.status} → ${status}?`))void mutate({action:'fulfilment.status',fulfilmentId:item.id,status,trackingUrl:tracking})}}>{status}</button>)}</div></div>)}</div></details>}
        <details className="mt-4 border-t border-rule pt-4"><summary className="cursor-pointer font-bold">Edition audit trail ({editionAudits.length})</summary><div className="mt-3 grid gap-2">{editionAudits.map(item=><p className="text-sm" key={item.id}><strong>{item.action}</strong> · {new Date(item.created_at).toLocaleString()} · {item.actor_user_id}</p>)}</div></details></article>})}</div></section></div>
}

function Catalogue({ data, busy, mutate }: { data: AdminData; busy: boolean; mutate: (p: Record<string,unknown>) => Promise<boolean> }) {
  const [preview,setPreview]=useState<Row|null>(null)
  async function submit(event: React.FormEvent<HTMLFormElement>, kind: string) { event.preventDefault(); const o=Object.fromEntries(new FormData(event.currentTarget)); if(await mutate({action:'catalog.upsert',kind,...o,active:kind==='discount'?o.active==='on':true})) event.currentTarget.reset() }
  async function previewDiscount(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const o=Object.fromEntries(new FormData(event.currentTarget)); const response=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:data.csrf,action:'discount.preview',...o})}); const result=await response.json() as {quote?:Row;error?:string}; setPreview(result.quote??{error:result.error}) }
  const field=(name:string,label:string,type='text',required=true)=><label className="mt-3 block" key={name}><span className="text-sm">{label}</span><input name={name} required={required} type={type} className={input}/></label>
  return <div className="grid gap-6 lg:grid-cols-2 xl:grid-cols-4">
    <form className={card} onSubmit={e=>void submit(e,'product')}><h2 className="text-2xl font-bold">Product</h2>{field('id','ID')}{field('name','Name')}{field('description','Description')}{field('baseMonthlyMinor','Base monthly price (minor units)','number')}<button disabled={busy} className={`${CTA} mt-4`}>Save</button></form>
    <form className={card} onSubmit={e=>void submit(e,'option')}><h2 className="text-2xl font-bold">Subscription option</h2>{field('id','ID')}{field('name','Name')}{field('durationMonths','Months','number')}{field('amountMinor','Legacy price in minor units','number')}{field('discountBasisPoints','Discount basis points','number')}{field('currency','Currency')}<button disabled={busy} className={`${CTA} mt-4`}>Save</button></form>
    <form className={card} onSubmit={e=>void submit(e,'discount')}><h2 className="text-2xl font-bold">Discount rules</h2>{field('id','ID')}{field('code','Code')}<label className="mt-3 block"><span className="text-sm">Type</span><select name="discountKind" className={input}><option>percentage</option><option>fixed</option><option>free_shipping</option></select></label>{field('value','Value (basis points or minor units)','number')}{field('startsAt','Starts','datetime-local',false)}{field('endsAt','Expires','datetime-local',false)}{field('usageLimit','Total usage limit','number',false)}{field('perCustomerLimit','Per-customer limit','number',false)}{field('minimumDurationMonths','Minimum duration','number',false)}{field('minimumOrderMinor','Minimum order (minor units)','number',false)}{field('eligibleDurations','Eligible months, comma-separated', 'text',false)}{field('eligibleCountries','Eligible country codes, comma-separated','text',false)}<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="combinable"/>Combine with duration discount</label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" name="active"/>Active</label><button disabled={busy} className={`${CTA} mt-4`}>Save rules</button></form>
    <form className={card} onSubmit={e=>void submit(e,'shipping')}><h2 className="text-2xl font-bold">Country, shipping and tax</h2>{field('countryCode','Country code')}{field('countryName','Country name')}{field('currency','Currency')}{field('shippingMinor','Base shipping','number')}{field('additionalCopyMinor','Each extra copy','number')}{field('taxRateBasisPoints','Tax basis points','number')}<button disabled={busy} className={`${CTA} mt-4`}>Save</button></form>
    <form className={`${card} lg:col-span-2`} onSubmit={previewDiscount}><h3 className="text-xl font-bold">Preview a saved offer</h3><p className="mt-2 text-sm">Inactive offers can be previewed after saving, but they will not apply to customer orders until activated.</p><div className="grid gap-3 sm:grid-cols-4">{field('discountCode','Code')}{field('durationMonths','Months','number')}{field('quantity','Quantity','number')}{field('countryCode','Country')}</div><button className={`${CTA_OUTLINE} mt-4`}>Preview outcome</button>{preview&&<pre className="mt-4 overflow-auto rounded-xl bg-graphite p-4 text-xs text-paper">{JSON.stringify(preview,null,2)}</pre>}</form>
    <section className={`${card} lg:col-span-2`}><h3 className="text-xl font-bold">Promotion performance</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Code</th><th>Redemptions</th><th>Revenue</th><th>Discount cost</th></tr></thead><tbody>{data.promotionReports.map(row=><tr className="border-t border-rule" key={row.id}><td className="py-2">{row.code}</td><td>{row.redemptions}</td><td>{row.revenue_minor}</td><td>{row.discount_cost_minor}</td></tr>)}</tbody></table></div></section>
    <section className="lg:col-span-2 xl:col-span-4"><h3 className="text-xl font-bold">Current configuration</h3><pre className="mt-3 max-h-80 overflow-auto rounded-xl bg-graphite p-4 text-xs text-paper">{JSON.stringify({products:data.products,options:data.options,discounts:data.discounts,zones:data.zones},null,2)}</pre></section>
  </div>
}

function Content({ data, busy, mutate }: { data: AdminData; busy: boolean; mutate: (p: Record<string,unknown>) => Promise<boolean> }) {
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f=new FormData(event.currentTarget); if(await mutate({action:'content.upsert',key:f.get('key'),title:f.get('title'),body:f.get('body')})) event.currentTarget.reset() }
  return <div className="grid gap-7 lg:grid-cols-[420px_1fr]"><form className={card} onSubmit={submit}><h2 className="text-2xl font-bold">Update managed content</h2><label className="mt-4 block">Content key<input className={input} name="key" placeholder="faq_delivery" required/></label><label className="mt-4 block">Title<input className={input} name="title" required/></label><label className="mt-4 block">Body<textarea className={`${input} min-h-40`} name="body" required/></label><button disabled={busy} className={`${CTA} mt-4`}>Save content</button></form><section><h2 className={H2}>Managed content</h2><div className="mt-5 grid gap-3">{data.content.map(row=><article className={card} key={row.content_key}><p className="font-mono text-xs uppercase">{row.content_key}</p><h3 className="mt-2 text-xl font-bold">{row.title}</h3><p className="mt-2 whitespace-pre-wrap">{row.body}</p></article>)}</div></section></div>
}

function Audit({ rows }: { rows: Row[] }) { return <section><h2 className={H2}>Audit trail</h2><div className="mt-6 grid gap-3">{rows.map(row=><article className={card} key={row.id}><div className="flex flex-wrap justify-between gap-2"><strong>{row.action}</strong><time>{new Date(row.created_at).toLocaleString()}</time></div><p className="mt-2 font-mono text-xs">{row.actor_user_id} · {row.target_type}:{row.target_id}</p><pre className="mt-2 overflow-auto text-xs">{JSON.stringify(JSON.parse(row.summary_json),null,2)}</pre></article>)}</div></section> }
