import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useRef, useState } from 'react'
import { SiteHeader } from '#/components/SiteHeader'
import { SiteFooter } from '#/components/Faq'
import { CTA, H2 } from '#/lib/uiKit'

type State='form'|'creating'|'failed'
type Quote={currency:string;subtotalMinor:number;durationDiscountMinor:number;offerDiscountMinor:number;shippingMinor:number;taxMinor:number;totalMinor:number}
const money=(minor:number,currency:string)=>new Intl.NumberFormat('en',{style:'currency',currency}).format(minor/100)

export const Route=createFileRoute('/checkout/stripe')({validateSearch:(s:Record<string,unknown>)=>({duration:Math.max(1,Number(s.duration??1)||1),quantity:Math.max(1,Number(s.quantity??1)||1),country:typeof s.country==='string'?s.country:'IN',code:typeof s.code==='string'?s.code:''}),component:StripePage})

function StripePage(){
  const search=Route.useSearch(),[state,setState]=useState<State>('form'),[error,setError]=useState(''),[csrf,setCsrf]=useState(''),[quote,setQuote]=useState<Quote|null>(null),[renewalQuote,setRenewalQuote]=useState<Quote|null>(null)
  const idempotencyKey=useRef(crypto.randomUUID())
  useEffect(()=>{
    const controller=new AbortController()
    void fetch('/api/session',{signal:controller.signal}).then(async response=>await response.json() as {csrf?:string}).then(result=>setCsrf(result.csrf??'')).catch(()=>{})
    const params=new URLSearchParams({duration:String(search.duration),quantity:String(search.quantity),country:search.country})
    async function load(){try{const renewalResponse=await fetch(`/api/pricing?${params}`,{signal:controller.signal});const renewal=await renewalResponse.json() as {quote?:Quote;error?:string};if(!renewalResponse.ok||!renewal.quote)throw new Error(renewal.error??'Pricing unavailable.');setRenewalQuote(renewal.quote);if(search.code)params.set('code',search.code);const response=await fetch(`/api/pricing?${params}`,{signal:controller.signal});const result=await response.json() as {quote?:Quote;error?:string};if(!response.ok||!result.quote)throw new Error(result.error??'Pricing unavailable.');setQuote(result.quote)}catch(error){if(!controller.signal.aborted)setError(error instanceof Error?error.message:'Pricing unavailable.')}}
    void load();return()=>controller.abort()
  },[search.duration,search.quantity,search.country,search.code])

  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();if(!csrf){location.href=`/login?returnTo=${encodeURIComponent(location.pathname+location.search)}`;return}
    setState('creating');setError('');const f=new FormData(event.currentTarget)
    const address={name:f.get('name'),line1:f.get('line1'),line2:f.get('line2'),city:f.get('city'),region:f.get('region'),postalCode:f.get('postalCode'),country:f.get('country')}
    try{const response=await fetch('/api/stripe/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf,idempotencyKey:idempotencyKey.current,durationMonths:search.duration,quantity:search.quantity,discountCode:search.code,email:f.get('email'),phone:f.get('phone'),address,acceptTerms:f.get('terms')==='on'})});const result=await response.json() as {url?:string;error?:string};if(!response.ok||!result.url)throw new Error(result.error??'Checkout unavailable.');location.assign(result.url)}catch(error){setError(error instanceof Error?error.message:'Checkout failed.');setState('failed')}
  }

  return <><SiteHeader/><main className="checkout-page mx-auto max-w-5xl px-4 py-12 md:py-20"><h1 className={H2}>Secure checkout</h1><p className="mt-3 text-graphite-soft">Stripe securely collects payment details. Offscroll Times never receives or stores raw card information.</p><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]">
    <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-graphite bg-paper-raised p-6 md:grid-cols-2"><input required name="name" placeholder="Full name" autoComplete="name" className="rounded-xl border p-3"/><input required name="email" type="email" placeholder="Email" autoComplete="email" className="rounded-xl border p-3"/><input required type="tel" name="phone" placeholder="Phone number" autoComplete="tel" className="rounded-xl border p-3 md:col-span-2"/><input required name="line1" placeholder="Address line 1" autoComplete="address-line1" className="rounded-xl border p-3 md:col-span-2"/><input name="line2" placeholder="Address line 2 (optional)" autoComplete="address-line2" className="rounded-xl border p-3 md:col-span-2"/><input required name="city" placeholder="City / town" autoComplete="address-level2" className="rounded-xl border p-3"/><input required name="region" placeholder="State / region" autoComplete="address-level1" className="rounded-xl border p-3"/><input required name="postalCode" placeholder="PIN code" autoComplete="postal-code" className="rounded-xl border p-3"/><select required name="country" defaultValue="IN" autoComplete="country" className="rounded-xl border p-3"><option value="IN">India</option></select><label className="flex items-start gap-3 md:col-span-2"><input required name="terms" type="checkbox" className="mt-1"/><span>I authorise automatic renewal every {search.duration} {search.duration===1?'month':'months'} until cancelled, and accept the <a href="/policies/subscription">subscription terms</a>, <a href="/policies/refund">cancellation policy</a> and <a href="/policies/privacy">privacy policy</a>.</span></label><button disabled={state==='creating'||!quote||!renewalQuote} className={`${CTA} md:col-span-2`}>{state==='creating'?'Creating subscription...':'Continue to Stripe'}</button>{error&&<p role="alert" className="text-red-700 md:col-span-2">{error}</p>}{state==='failed'&&<button type="button" onClick={()=>setState('form')} className="underline md:col-span-2">Return and retry safely</button>}</form>
    <aside className="rounded-2xl border-2 border-graphite bg-sun p-6"><h2 className="text-2xl font-bold">Order summary</h2><dl className="mt-5 grid gap-3"><div className="flex justify-between"><dt>Duration</dt><dd>{search.duration} months</dd></div><div className="flex justify-between"><dt>Copies each month</dt><dd>{search.quantity}</dd></div><div className="flex justify-between"><dt>Total copies</dt><dd>{search.duration*search.quantity}</dd></div>{quote&&<><div className="flex justify-between"><dt>Subtotal</dt><dd>{money(quote.subtotalMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Discount</dt><dd>−{money(quote.durationDiscountMinor+quote.offerDiscountMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Delivery</dt><dd>{money(quote.shippingMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Tax</dt><dd>{money(quote.taxMinor,quote.currency)}</dd></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><dt>Initial payment</dt><dd>{money(quote.totalMinor,quote.currency)}</dd></div></>}</dl>{renewalQuote&&<p className="mt-4 font-bold">Then {money(renewalQuote.totalMinor,renewalQuote.currency)} every {search.duration} {search.duration===1?'month':'months'} until cancelled.</p>}<p className="mt-5 text-xs">The initial payment covers the full selected term. Stripe automatically charges for the same duration and quantity at renewal unless cancelled. First-term promotions end after the first term; the regular renewal amount is shown on Stripe before you authorise payment.</p></aside>
  </div></main><SiteFooter/></>
}
