import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useRef, useState } from 'react'
import { SiteHeader } from '#/components/SiteHeader'
import { SiteFooter } from '#/components/Faq'
import { CTA, H2 } from '#/lib/uiKit'

declare global { interface Window { Razorpay?: new(options:Record<string,unknown>)=>{open():void;on(event:string,callback:(response:unknown)=>void):void} } }
type State='form'|'creating'|'paying'|'verifying'|'success'|'failed'|'cancelled'|'timeout'
type Quote={currency:string;subtotalMinor:number;durationDiscountMinor:number;offerDiscountMinor:number;shippingMinor:number;taxMinor:number;totalMinor:number}
const money=(minor:number,currency:string)=>new Intl.NumberFormat('en',{style:'currency',currency}).format(minor/100)

export const Route=createFileRoute('/checkout/razorpay')({validateSearch:(s:Record<string,unknown>)=>({duration:Math.max(1,Number(s.duration??1)||1),quantity:Math.max(1,Number(s.quantity??1)||1),country:typeof s.country==='string'?s.country:'IN',code:typeof s.code==='string'?s.code:''}),component:RazorpayPage})

function RazorpayPage(){
  const search=Route.useSearch(),[state,setState]=useState<State>('form'),[error,setError]=useState(''),[csrf,setCsrf]=useState(''),[quote,setQuote]=useState<Quote|null>(null)
  const idempotencyKey=useRef(crypto.randomUUID())
  useEffect(()=>{void fetch('/api/session').then(async r=>(await r.json()) as {csrf?:string}).then(x=>setCsrf(x.csrf??''));void fetch(`/api/pricing?duration=${search.duration}&quantity=${search.quantity}&country=${encodeURIComponent(search.country)}&code=${encodeURIComponent(search.code)}`).then(async r=>{const result=await r.json() as {quote?:Quote;error?:string};if(r.ok&&result.quote)setQuote(result.quote);else setError(result.error??'Pricing is unavailable.')});const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;document.head.appendChild(script);return()=>{script.remove()}},[search.duration,search.quantity,search.country,search.code])
  async function recordState(orderId:string,paymentState:'cancelled'|'timed_out'){await fetch('/api/razorpay/checkout',{method:'POST',headers:{'Content-Type':'application/json'},keepalive:true,body:JSON.stringify({action:'record_state',csrf,orderId,paymentState})}).catch(()=>undefined)}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!csrf){location.href=`/login?returnTo=${encodeURIComponent(location.pathname+location.search)}`;return}setState('creating');setError('');const f=new FormData(event.currentTarget),address={name:f.get('name'),line1:f.get('line1'),line2:f.get('line2'),city:f.get('city'),region:f.get('region'),postalCode:f.get('postalCode'),country:f.get('country')}
    try{const response=await fetch('/api/razorpay/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',csrf,idempotencyKey:idempotencyKey.current,durationMonths:search.duration,quantity:search.quantity,discountCode:search.code,email:f.get('email'),phone:f.get('phone'),address,acceptTerms:f.get('terms')==='on'})});const order=await response.json() as Record<string,any>;if(!response.ok)throw new Error(order.error??'Order could not be created.');setQuote(order.quote as Quote);if(!window.Razorpay)throw new Error('Secure payment window did not load.');setState('paying');const timer=window.setTimeout(()=>{void recordState(order.orderId,'timed_out');setState('timeout')},15*60*1000);const checkout=new window.Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,order_id:order.orderId,name:'Offscroll Times',description:`${search.duration}-month subscription · ${search.quantity} copies`,prefill:{name:f.get('name'),email:f.get('email'),contact:f.get('phone')},modal:{ondismiss:()=>{clearTimeout(timer);void recordState(order.orderId,'cancelled');setState('cancelled')}},handler:async(result:Record<string,string>)=>{clearTimeout(timer);setState('verifying');try{const verify=await fetch('/api/razorpay/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify',csrf,...result})});const verified=await verify.json() as {status?:string;error?:string};if(!verify.ok)throw new Error(verified.error??'Verification failed.');setState(verified.status==='captured'?'success':'verifying')}catch(error){setError(error instanceof Error?error.message:'Payment verification failed.');setState('failed')}}});checkout.on('payment.failed',()=>{clearTimeout(timer);setError('Payment failed. No subscription has been activated. Please try again.');setState('failed')});checkout.open()}catch(e){setError(e instanceof Error?e.message:'Payment failed.');setState('failed')}}
  if(state==='success')return <><SiteHeader/><main className="mx-auto max-w-2xl px-5 py-24 text-center"><h1 className={H2}>Payment captured.</h1><p>Your verified subscription, receipt and expected dispatch are available in your account.</p><a className={CTA} href="/account">View account</a></main><SiteFooter/></>
  return <><SiteHeader/><main className="checkout-page mx-auto max-w-5xl px-4 py-12 md:py-20"><h1 className={H2}>Secure checkout</h1><p className="mt-3 text-graphite-soft">Razorpay securely collects payment details. Offscroll Times never receives or stores raw card information.</p><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]">
    <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-graphite bg-paper-raised p-6 md:grid-cols-2"><input required name="name" placeholder="Full name" autoComplete="name" className="rounded-xl border p-3"/><input required name="email" type="email" placeholder="Email" autoComplete="email" className="rounded-xl border p-3"/><input name="phone" placeholder="Phone (optional)" autoComplete="tel" className="rounded-xl border p-3 md:col-span-2"/><input required name="line1" placeholder="Address line 1" autoComplete="address-line1" className="rounded-xl border p-3 md:col-span-2"/><input name="line2" placeholder="Address line 2 (optional)" autoComplete="address-line2" className="rounded-xl border p-3 md:col-span-2"/><input required name="city" placeholder="City / town" autoComplete="address-level2" className="rounded-xl border p-3"/><input name="region" placeholder="State" autoComplete="address-level1" className="rounded-xl border p-3"/><input required name="postalCode" placeholder="PIN code" autoComplete="postal-code" className="rounded-xl border p-3"/><select required name="country" defaultValue="IN" autoComplete="country" className="rounded-xl border p-3"><option value="IN">India</option></select><label className="flex items-start gap-3 md:col-span-2"><input required name="terms" type="checkbox" className="mt-1"/><span>I accept the <a href="/policies/subscription">subscription terms</a>, <a href="/policies/refund">cancellation policy</a> and <a href="/policies/privacy">privacy policy</a>.</span></label><button disabled={state==='creating'||state==='paying'||state==='verifying'} className={`${CTA} md:col-span-2`}>{state==='creating'?'Creating secure order…':state==='verifying'?'Verifying payment…':'Continue to Razorpay'}</button>{error&&<p role="alert" className="text-red-700 md:col-span-2">{error}</p>}{['failed','cancelled','timeout'].includes(state)&&<button type="button" onClick={()=>setState('form')} className="underline md:col-span-2">Return and retry safely</button>}</form>
    <aside className="rounded-2xl border-2 border-graphite bg-sun p-6"><h2 className="text-2xl font-bold">Order summary</h2><dl className="mt-5 grid gap-3"><div className="flex justify-between"><dt>Duration</dt><dd>{search.duration} months</dd></div><div className="flex justify-between"><dt>Copies each month</dt><dd>{search.quantity}</dd></div><div className="flex justify-between"><dt>Total copies</dt><dd>{search.duration*search.quantity}</dd></div>{quote&&<><div className="flex justify-between"><dt>Subtotal</dt><dd>{money(quote.subtotalMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Discount</dt><dd>−{money(quote.durationDiscountMinor+quote.offerDiscountMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Delivery</dt><dd>{money(quote.shippingMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Tax</dt><dd>{money(quote.taxMinor,quote.currency)}</dd></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><dt>Payable</dt><dd>{money(quote.totalMinor,quote.currency)}</dd></div></>}</dl><p className="mt-5 text-xs">The server recalculates this total before Razorpay opens. Browser success remains pending until server verification completes.</p></aside>
  </div></main><SiteFooter/></>
}
