import { createFileRoute, notFound } from '@tanstack/react-router'
import { SiteHeader } from '#/components/SiteHeader'
import { SiteFooter } from '#/components/Faq'
import { BRAND_NAME, BUSINESS_DETAILS, CONTACT_EMAIL, CONTACT_HOURS, WHATSAPP_URL } from '#/content/site'

type Section = { heading: string; paragraphs?: string[]; bullets?: string[] }
type Policy = { title: string; summary: string; sections: Section[] }
const updated = '27 August 2026'
const identityNotice = `The legal entity name, registered address, registration and tax identifiers, and named grievance contact must be inserted before launch. Current support: ${CONTACT_EMAIL}.`

const POLICIES: Record<string, Policy> = {
  terms: { title: 'Terms and Conditions', summary: `These terms govern purchases and use of ${BRAND_NAME}. They are a pre-launch draft and do not limit rights that cannot lawfully be excluded.`, sections: [
    { heading: 'Who we are', paragraphs: [identityNotice] },
    { heading: 'The publication', paragraphs: [`${BRAND_NAME} is a physical, monthly puzzle publication. Issue themes, puzzles and difficulty may vary. Content is for entertainment and general educational enjoyment.`] },
    { heading: 'Orders and payment', paragraphs: ['You must provide accurate contact, billing and delivery information. Google or Microsoft provides sign-in; Razorpay provides hosted, tokenised payment processing. We do not receive or store raw card details.', 'An order is accepted only after server-side payment confirmation. Checkout shows the term, quantity, tax, delivery charge, discounts and total before payment authorisation.'] },
    { heading: 'Consumer rights', paragraphs: ['Nothing in these terms excludes statutory consumer remedies, withdrawal rights, guarantees or other mandatory protections in the country where you live. If these terms conflict with mandatory law, that law prevails.'] },
    { heading: 'Intellectual property', paragraphs: ['The publication and website content may be used personally or within the quantity and licence purchased. Copying, resale or commercial redistribution without written permission is prohibited.'] },
    { heading: 'Liability and governing law', paragraphs: ['We do not exclude liability where doing so would be unlawful. Governing-law, jurisdiction and dispute-resolution clauses require qualified review for the legal entity and each country served before launch.'] },
  ]},
  subscription: { title: 'Subscription and Renewal Terms', summary: 'A subscription is a one-time, prepaid purchase for the selected number of monthly editions. Renewal is manual.', sections: [
    { heading: 'Term and entitlement', paragraphs: ['Choose 1, 3, 6 or 12 months and a quantity. Total entitlement is the months multiplied by monthly quantity. Start date, paid-through date and expected first edition are recorded with the order.'] },
    { heading: 'Manual renewal', paragraphs: ['We do not automatically renew or make a future charge. An in-account reminder appears near the end; continuing requires a new selection and payment authorisation.'] },
    { heading: 'Cut-off, pause and cancellation', paragraphs: ['Orders and address changes received by the displayed cut-off normally apply to the next eligible edition. A confirmed pause may move dispatch to a later edition.', 'Cancellation does not automatically erase paid entitlement or create a refund. Mandatory withdrawal and refund rights remain available.'] },
    { heading: 'Changes', paragraphs: ['Later price changes never alter a completed order. Material service changes affecting a paid term will be explained before they take effect.'] },
  ]},
  delivery: { title: 'Shipping and Delivery Policy', summary: 'We dispatch monthly across India with free delivery. International customers must enquire before ordering.', sections: [
    { heading: 'Schedule and estimates', paragraphs: ['Checkout identifies the first eligible edition and estimated dispatch date. Typical transit is 3–7 business days in India after dispatch. This is an estimate, not a guarantee. International checkout is not currently available.'] },
    { heading: 'Addresses and tracking', paragraphs: ['You are responsible for an accurate deliverable address. Changes confirmed before the account cut-off apply to the next unlocked fulfilment list; later changes apply to a following edition. Tracking is supplied where supported.'] },
    { heading: 'Taxes, duties and charges', paragraphs: ['Checkout discloses delivery and tax collected by us before payment. Before launch, the importer of record and any unavoidable import VAT, customs duty or handling fee must be identified and disclosed before ordering; hidden post-purchase charges are not acceptable.'] },
    { heading: 'Problems', paragraphs: ['Report a delayed, missing, damaged or returned issue through Contact or WhatsApp with the order reference. We will investigate and provide a replacement, redelivery or refund where required.'] },
  ]},
  refund: { title: 'Cancellation, Return, Refund and Replacement Policy', summary: 'Our 7-day business cancellation promise supplements—rather than replaces—mandatory consumer rights.', sections: [
    { heading: 'Our 7-day promise', paragraphs: ['You may request cancellation within 7 days of purchase for a full refund if the first issue has not entered preparation or dispatch. If preparation has begun, we will explain any lawful deduction or alternative before acting.'] },
    { heading: 'European withdrawal rights', paragraphs: ['Where European distance-selling law applies, an eligible consumer subscription generally has a 14-day withdrawal period from conclusion of the contract. The newspaper and periodical exception does not remove the withdrawal right for subscriptions. Any lawful exception or deduction must be explained case by case.', 'Send an unambiguous request through Contact, email or WhatsApp with your name and order reference. Where withdrawal applies, reimbursement will use the original payment method within the legally required period.'] },
    { heading: 'Damaged, defective or missing copies', paragraphs: ['Contact us within 14 days of delivery—or the expected date for a missing copy—with the order reference and, where helpful, photographs. We will arrange replacement, redelivery or refund. This reporting window does not shorten mandatory remedies or guarantees.'] },
    { heading: 'Refund processing', paragraphs: ['Approved refunds are submitted to Razorpay and recorded against the original order. Bank processing time is outside our control. Cancelling manual renewal alone does not refund editions already correctly supplied.'] },
  ]},
  privacy: { title: 'Privacy Policy', summary: `This notice explains how ${BRAND_NAME} handles personal data for accounts, orders, delivery, support and legal compliance.`, sections: [
    { heading: 'Controller and contact', paragraphs: [identityNotice] },
    { heading: 'Data we use', bullets: ['Google or Microsoft identity identifier, name and verified account claims.', 'Delivery and billing address versions, phone where needed, and order details.', 'Subscription, fulfilment, shipment, enquiry, refund and audit records.', 'Razorpay payment identifiers, status and amount—not raw card details.', 'Essential session, rate-limit and fraud-prevention signals.'] },
    { heading: 'Purposes and legal bases', paragraphs: ['We use data to perform the purchase and delivery contract, meet tax and consumer-law obligations, secure the service under legitimate interests where permitted, and respond to requests. Future non-essential marketing requires a separate valid choice and is not a condition of purchase.'] },
    { heading: 'Recipients and transfers', paragraphs: ['Necessary data may be shared with Google or Microsoft for sign-in, Razorpay for payment, Cloudflare for hosting, and printers, couriers or advisers where operationally necessary. Contact enquiries are stored for support and shared with FormSubmit to forward your name, reply email, country, enquiry details and message to hello@offscrolltimes.com. Before European launch, transfer locations and required safeguards must be documented. We do not sell personal data.'] },
    { heading: 'Retention', paragraphs: ['Account and fulfilment data is kept while needed to provide service. Financial and tax records remain for the legally required period; support and security records follow documented schedules. Data is deleted or anonymised when no longer required, subject to legal holds.'] },
    { heading: 'Your rights', paragraphs: ['Depending on location, you may request access, correction, deletion, restriction, portability or objection, withdraw consent, and complain to a regulator. Use profile privacy controls or contact support. We aim to answer within one month where GDPR applies.'] },
    { heading: 'Children and security', paragraphs: ['The service is not directed to children purchasing independently. We use access controls, encryption in transit, audit records and limited retention. We do not make solely automated decisions producing legal or similarly significant effects.'] },
  ]},
  cookies: { title: 'Cookie Policy and Preferences', summary: 'The service uses essential storage and offers a separate choice for anonymous, first-party analytics. No advertising or third-party marketing tracker is used.', sections: [
    { heading: 'What is used', bullets: ['A secure, HttpOnly, SameSite session cookie for account access.', 'Short-lived OAuth state, nonce and PKCE values needed for Google or Microsoft sign-in.', 'Session storage remembering whether the decorative envelope introduction opened during the browser session.', 'Local storage recording whether anonymous first-party analytics were allowed or declined.'] },
    { heading: 'Anonymous analytics', paragraphs: ['Only after you choose Allow analytics, we count page paths, duration selections and checkout starts. The analytics event does not contain your name, email, coupon code, account identifier or full URL query. Successful payments, failures and fulfilment are operational records required to provide and administer the service.', 'Choose Decline to prevent browser analytics. Use Reset analytics preference below at any time; the consent question will appear again and no non-essential measurement resumes unless you actively allow it.'] },
    { heading: 'Future non-essential cookies', paragraphs: ['Any future non-essential storage will remain blocked until the legally required opt-in. Withdrawal must remain as easy as giving consent.'] },
  ]},
  accessibility: { title: 'Accessibility Statement', summary: `We want ${BRAND_NAME} to be usable by as many people as possible and target WCAG 2.2 level AA.`, sections: [
    { heading: 'What we support', bullets: ['Semantic headings, labelled controls and keyboard navigation.', 'Visible focus, readable contrast and responsive layouts.', 'Reduced-motion support for animation.', 'Status and validation messages exposed to assistive technology.'] },
    { heading: 'Known limitations', paragraphs: ['Concept artwork may not yet provide the same information as final product photography. Full assistive-technology and browser coverage remains a pre-launch verification task.'] },
    { heading: 'Feedback', paragraphs: [`Contact ${CONTACT_EMAIL} or WhatsApp with the page, device and assistance needed. We aim to acknowledge accessibility feedback within two business days and offer an accessible alternative while investigating.`] },
  ]},
  contact: { title: 'Business and Grievance Contact', summary: 'Support channels are active; statutory business and grievance particulars remain a launch blocker.', sections: [
    { heading: 'Customer support', bullets: [`Email: ${CONTACT_EMAIL}`, `Business hours: ${CONTACT_HOURS.india}`, CONTACT_HOURS.responseTime, `Operating location: ${BUSINESS_DETAILS.location}`, 'Contact form: /contact', 'WhatsApp: use the button below.'] },
    { heading: 'Required before launch', paragraphs: [identityNotice, 'Add the named India grievance officer, postal grievance address, response timelines, and the European trader/importer contact where applicable. Do not take live orders until these particulars are published.'] },
  ]},
}

export const Route = createFileRoute('/policies/$slug')({ loader: ({ params }) => { const policy = POLICIES[params.slug]; if (!policy) throw notFound(); return policy }, head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.title} | ${BRAND_NAME}` : 'Policy' }] }), component: PolicyPage })

function PolicyPage() {
  const policy = Route.useLoaderData()
  return <><SiteHeader/><main className="mx-auto max-w-[760px] px-5 py-16 md:py-24"><p className="mb-4 font-mono text-[11px] tracking-[0.16em] text-graphite-mute uppercase">Legal · Updated {updated}</p><h1 className="mb-4 font-display text-[clamp(1.9rem,4.6vw,2.8rem)] leading-[1.02] font-bold tracking-[-0.03em]">{policy.title}</h1><p className="mb-10 text-lg leading-relaxed text-graphite-soft">{policy.summary}</p><div className="flex flex-col gap-9">{policy.sections.map(section=><section key={section.heading}><h2 className="mb-3 font-display text-2xl font-bold">{section.heading}</h2><div className="grid gap-3 leading-relaxed text-graphite-soft">{section.paragraphs?.map(p=><p key={p}>{p}</p>)}{section.bullets&&<ul className="list-disc space-y-2 pl-6">{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>}</div></section>)}</div>{Route.useParams().slug==='cookies'&&<button className="mt-8 rounded-full border border-graphite px-5 py-3 font-bold" onClick={()=>{localStorage.removeItem('offscroll_analytics_choice');location.reload()}}>Reset analytics preference</button>}<nav aria-label="Related legal policies" className="mt-12 flex flex-wrap gap-3 border-t border-graphite/20 pt-7">{Object.entries(POLICIES).map(([slug,item])=><a key={slug} href={`/policies/${slug}`} className="rounded-full border border-graphite px-4 py-2 text-sm no-underline hover:bg-graphite hover:text-paper">{item.title}</a>)}</nav><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="mt-7 inline-block rounded-full bg-graphite px-6 py-3.5 font-mono text-[12.5px] font-bold tracking-[0.08em] text-paper uppercase no-underline">Message us on WhatsApp</a></main><SiteFooter/></>
}
