export const ADMIN_EXPORTS = [
  ['customers','Customers','Names, email, phone, WhatsApp and current delivery address'],
  ['addresses','Delivery addresses','Complete delivery address history'],
  ['orders','Orders','Order details and pricing snapshots'],
  ['subscriptions','Subscriptions','Plans, subscription status and paid entitlement'],
  ['payments','Payments','Recorded payment amounts and status'],
  ['refunds','Refunds','Refund amounts and status'],
  ['shipments','Shipments','Shipping records and tracking'],
  ['fulfilments','Fulfilments','Edition delivery and dispatch status'],
  ['editions','Editions','Issue dates, cutoffs and status'],
  ['eligibility','Edition eligibility','Included and excluded subscriptions'],
  ['newsletter','Email subscribers','Email signup status and consent history'],
  ['enquiries','Contact enquiries','Customer messages and support notes'],
  ['discounts','Discount offers','Offer codes, rules and validity'],
  ['redemptions','Discount redemptions','Recorded use of offers'],
  ['products','Products','Product catalogue'],
  ['plans','Subscription plans','Available plan settings'],
  ['shipping-zones','Shipping zones','Delivery pricing configuration'],
  ['content','Website content','Saved content entries'],
  ['account-events','Account events','Subscription and account activity'],
  ['privacy-requests','Privacy requests','Customer privacy request history'],
  ['email-delivery','Email delivery','Transactional message delivery status'],
  ['files','File records','Uploaded file metadata; download file contents from the Files tab'],
  ['analytics','Analytics events','Recorded page visits and subscription funnel activity'],
  ['audit','Admin audit history','Recorded admin actions'],
] as const
