import { useEffect, useState } from 'react'
import { CTA_OUTLINE, H2 } from '#/lib/uiKit'
type Subscriber={id:string;email:string;status:string;consent_at:number}
type Result={subscribers:Subscriber[];page:number;pages:number;total:number}
export function AdminNewsletter({mutate}:{mutate:(payload:Record<string,unknown>)=>Promise<boolean>}) {
 const [data,setData]=useState<Result|null>(null),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');void fetch(`/api/newsletter?page=${page}`,{signal:controller.signal}).then(async response=>{const result=await response.json() as Result&{error?:string};if(!response.ok)throw new Error(result.error||'Subscribers could not be loaded.');setData(result)}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'Please retry.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[page,revision])
 async function unsubscribe(id:string){setBusy(true);try{if(await mutate({action:'newsletter.unsubscribe',subscriberId:id}))setRevision(value=>value+1)}finally{setBusy(false)}}
 return <section><h2 className={H2}>Email signups</h2><p className="mt-3">People who opted into email updates. These signups are separate from paid newspaper subscriptions; email ownership has not been verified.</p>{loading&&<p role="status" className="mt-4">Loading email signups…</p>}{error&&<div role="alert" className="mt-4"><p>{error}</p><button className={CTA_OUTLINE} onClick={()=>setRevision(value=>value+1)}>Retry</button></div>}{!loading&&!error&&data&&<><p className="my-4">{data.total} signups</p><div className="grid gap-3">{data.subscribers.map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-graphite p-4"><div><strong>{row.email}</strong><p className="mt-1 text-sm">{row.status} · Consent recorded {new Date(row.consent_at).toLocaleDateString()}</p></div>{row.status==='subscribed'&&<button disabled={busy} className={CTA_OUTLINE} onClick={()=>void unsubscribe(row.id)}>Unsubscribe</button>}</article>)}{!data.total&&<p>No email signups yet.</p>}</div><nav aria-label="Email signup pages" className="mt-5 flex items-center gap-3"><button className={CTA_OUTLINE} disabled={data.page<=1} onClick={()=>setPage(data.page-1)}>Previous</button><span>{data.page} / {data.pages}</span><button className={CTA_OUTLINE} disabled={data.page>=data.pages} onClick={()=>setPage(data.page+1)}>Next</button></nav></>}</section>
}
