import { useEffect,useState } from 'react'
import { CTA, EYEBROW, H2 } from '#/lib/uiKit'

type FileRow={id:string;category:string;related_id:string;original_name:string;content_type:string;size_bytes:number;visibility:string;created_at:number}
export function AdminFileLibrary({csrf}:{csrf:string}){
  const [files,setFiles]=useState<FileRow[]>([]),[status,setStatus]=useState('')
  async function load(){const r=await fetch('/api/admin/files');if(r.ok)setFiles(((await r.json()) as {files:FileRow[]}).files)}
  useEffect(()=>{void load()},[])
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),file=data.get('file') as File,category=String(data.get('category')),relatedId=String(data.get('relatedId'));if(!file?.size)return
    setStatus('Uploading…');const response=await fetch('/api/admin/files',{method:'POST',headers:{'Content-Type':file.type,'X-File-Size':String(file.size),'X-CSRF-Token':csrf,'X-File-Category':category,'X-Related-Id':relatedId,'X-File-Name':file.name,'X-Publish':data.get('publish')==='on'?'true':'false'},body:file});const result=await response.json() as {error?:string};setStatus(response.ok?'File stored securely.':result.error??'Upload failed.');if(response.ok){form.reset();await load()}}
  return <section><p className={EYEBROW}>Private object storage</p><h2 className={H2}>Edition and product files</h2><form className="mt-6 grid gap-4 rounded-2xl border border-graphite bg-paper p-6 md:grid-cols-2" onSubmit={event=>void submit(event)}><label>Category<select name="category" className="mt-1 block w-full rounded-xl border p-3"><option value="product_asset">Product image</option><option value="edition_file">Private edition PDF</option></select></label><label>Product or edition ID<input required name="relatedId" className="mt-1 block w-full rounded-xl border p-3"/></label><label className="md:col-span-2">File<input required name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-1 block w-full rounded-xl border p-3"/></label><label className="flex gap-2"><input name="publish" type="checkbox"/> Publish asset through the public asset endpoint</label><button className={CTA}>Upload file</button>{status&&<p role="status" className="md:col-span-2">{status}</p>}</form><div className="mt-6 grid gap-3">{files.map(file=><article key={file.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-graphite bg-paper p-4"><div><strong>{file.original_name}</strong><p className="text-sm">{file.category} · {file.related_id} · {(file.size_bytes/1024).toFixed(1)} KB · {file.visibility}</p></div><a className="underline" href={`/api/admin/file/${file.id}`}>Download</a></article>)}</div></section>
}
