import { useState } from 'react'
import { CTA, CTA_OUTLINE, EYEBROW } from '#/lib/uiKit'

type Influencer={id:string;code:string;discount_basis_points:number}
export function AdminReferrals({basisPoints,influencerReferrals,busy,mutate}:{basisPoints:number;influencerReferrals:Influencer[];busy:boolean;mutate:(payload:Record<string,unknown>)=>Promise<boolean>}){
  const [percentage,setPercentage]=useState(String(basisPoints/100)),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Influencer|null>(null)
  async function saveSetting(event:React.FormEvent){event.preventDefault();setNotice('');if(await mutate({action:'referral.settings',percentage:Number(percentage)}))setNotice(`Saved: ${Number(percentage)}% customer referral discount is active.`)}
  async function saveInfluencer(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setNotice('');if(await mutate({action:'influencer_referral.save',referralId:editing?.id,code:form.get('code'),percentage:Number(form.get('percentage'))})){setNotice(`Saved influencer referral code ${String(form.get('code')).toUpperCase()}.`);setEditing(null);event.currentTarget.reset()}}
  async function remove(row:Influencer){if(!window.confirm(`Delete influencer referral code ${row.code}?`))return;if(await mutate({action:'influencer_referral.delete',referralId:row.id,confirm:true}))setNotice(`Deleted ${row.code}.`)}
  return <div className="grid max-w-4xl gap-7"><section className="rounded-2xl border border-graphite bg-paper p-6"><p className={EYEBROW}>Customer referrals</p><h2 className="mt-2 text-2xl font-bold">Referral discount</h2><p className="mt-2 text-sm text-graphite-soft">Every customer has a unique code. It may be redeemed once by a new customer on their first paid subscription.</p><form onSubmit={event=>void saveSetting(event)} className="mt-6 flex flex-wrap items-end gap-4"><label className="w-full max-w-xs text-sm font-bold">Discount percentage<input required min="0" max="100" step="0.01" type="number" value={percentage} onChange={event=>setPercentage(event.target.value)} className="mt-1 w-full rounded-xl border border-graphite bg-white px-3 py-2"/></label><button disabled={busy} className={CTA}>Save referral setting</button></form></section><section className="rounded-2xl border border-graphite bg-paper p-6"><p className={EYEBROW}>Influencer referral codes</p><h2 className="mt-2 text-2xl font-bold">Create an influencer code</h2><p className="mt-2 text-sm text-graphite-soft">These work in the same referral-code field at subscription and checkout. Each code can have its own percentage.</p><form key={editing?.id??'new'} onSubmit={event=>void saveInfluencer(event)} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Influencer referral code<input required name="code" defaultValue={editing?.code??''} pattern="[A-Za-z0-9_-]{3,50}" placeholder="CREATOR10" className="mt-1 w-full rounded-xl border border-graphite bg-white px-3 py-2"/></label><label className="text-sm font-bold">Discount percentage<input required name="percentage" type="number" min="0" max="100" step="0.01" defaultValue={editing?String(editing.discount_basis_points/100):''} className="mt-1 w-full rounded-xl border border-graphite bg-white px-3 py-2"/></label><div className="flex flex-wrap gap-3 sm:col-span-2"><button disabled={busy} className={CTA}>{editing?'Save changes':'Create influencer code'}</button>{editing&&<button type="button" className={CTA_OUTLINE} onClick={()=>setEditing(null)}>Cancel</button>}</div></form><div className="mt-7 grid gap-3">{influencerReferrals.length?influencerReferrals.map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-rule p-4"><div><strong>{row.code}</strong><p className="text-sm text-graphite-soft">{Number(row.discount_basis_points)/100}% discount</p></div><div className="flex gap-2"><button disabled={busy} className={CTA_OUTLINE} onClick={()=>setEditing(row)}>Edit</button><button disabled={busy} className={CTA_OUTLINE} onClick={()=>void remove(row)}>Delete</button></div></article>):<p className="text-sm text-graphite-soft">No influencer referral codes created yet.</p>}</div></section>{notice&&<p role="status" className="rounded-xl border border-graphite bg-sun p-3 text-sm">{notice}</p>}</div>
}
