import { SiteHeader } from '#/components/SiteHeader'
import { SiteFooter } from '#/components/Faq'
import { CTA, CTA_OUTLINE, EYEBROW } from '#/lib/uiKit'

export function AuthPage({ mode, returnTo }: { mode:'login'|'register'; returnTo:string }) {
  const login=mode==='login'
  const safeReturn=returnTo.startsWith('/')&&!returnTo.startsWith('//')?returnTo:'/account'
  return <><SiteHeader/><main id="main-content" className="mx-auto grid min-h-[68vh] max-w-[1100px] items-center gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[1fr_460px] lg:px-10">
    <section className="max-w-xl"><p className={EYEBROW}>{login?'Welcome back':'Join Offscroll Times'}</p><h1 className="mt-3 font-display text-[clamp(2.8rem,7vw,5.4rem)] font-bold leading-[.9] tracking-[-.05em]">{login?'Your puzzles are waiting.':'Create your Offscroll Times account.'}</h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-graphite-soft">{login?'Sign in to view paid copies, delivery dates, addresses, dispatch history and receipts.':'Create one secure account for subscriptions, delivery updates, invoices and support.'}</p><div className="mt-8 grid max-w-md gap-3 sm:grid-cols-3">{['Google or Microsoft','Private records','Manual renewal'].map(item=><div key={item} className="rounded-xl border border-graphite bg-sun/30 p-3 text-center font-mono text-[10px] font-bold uppercase">{item}</div>)}</div></section>
    <section className="rounded-3xl border-2 border-graphite bg-paper-raised p-7 shadow-[8px_8px_0_#171512] sm:p-9" aria-labelledby="auth-title"><p className={EYEBROW}>Customer account</p><h2 id="auth-title" className="mt-3 font-display text-4xl font-bold">{login?'Sign in':'Create account'}</h2><p className="mt-4 leading-relaxed text-graphite-soft">Choose an identity provider. Offscroll Times never receives or stores your provider password.</p><div className="mt-7 grid gap-3"><a className={`${CTA} flex w-full justify-center`} href={`/auth/google/start?return_to=${encodeURIComponent(safeReturn)}`}>Continue with Google</a><a className={`${CTA_OUTLINE} flex w-full justify-center`} href={`/auth/microsoft/start?return_to=${encodeURIComponent(safeReturn)}`}>Continue with Microsoft</a></div><div className="my-6 h-px bg-rule"/><p className="text-center text-sm">{login?'First visit? Your account is created securely after provider verification.':'Already registered? The same buttons sign you in.'}</p><a className="mt-3 block text-center text-sm underline" href={`${login?'/register':'/login'}?returnTo=${encodeURIComponent(safeReturn)}`}>{login?'Learn about account creation':'Return to sign in'}</a><p className="mt-6 text-center text-xs leading-relaxed text-graphite-mute">By continuing, you agree to our <a href="/policies/terms">Terms</a> and acknowledge our <a href="/policies/privacy">Privacy Policy</a>.</p></section>
  </main><SiteFooter/></>
}
