import { useEffect, useState } from 'react'
import { Reveal } from '#/components/Reveal'
import type { PricingQuote } from '#/lib/pricing.server'
import { firstEditionDate, formatLongDate } from '#/lib/dates'
import { CTA, EYEBROW, SHELL } from '#/lib/uiKit'

const DURATIONS = [1, 3, 12] as const
const FALLBACK_COUNTRIES = [
  { code:'IN', name:'India', transit:'3–7 business days' },
] as const

function money(minor:number,currency:string){return new Intl.NumberFormat('en',{style:'currency',currency}).format(minor/100)}

export function SubscriptionConfigurator(){
  const [months,setMonths]=useState(3),[quantity,setQuantity]=useState<number|string>(1),[countryCode,setCountryCode]=useState('IN'),[offer,setOffer]=useState('')
  const [countries,setCountries]=useState<Array<{code:string;name:string;currency?:string;transit?:string}>>([{code:'IN',name:'India'}])
  const [quote,setQuote]=useState<PricingQuote|null>(null),[state,setState]=useState<'loading'|'ready'|'error'>('loading')
  useEffect(()=>{void fetch('/api/pricing?catalog=1').then(async response=>response.ok?await response.json() as {countries?:Array<{code:string;name:string;currency?:string}>}:null).then(result=>{if(!result?.countries?.length)return;setCountries(result.countries)}).catch(()=>undefined)},[])
  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(async()=>{setState('loading');const params=new URLSearchParams({duration:String(months),quantity:String(Number(quantity)||1),country:countryCode});if(offer.trim())params.set('code',offer.trim());try{const response=await fetch(`/api/pricing?${params}`,{headers:{Accept:'application/json'},signal:controller.signal});const result=await response.json() as {quote?:PricingQuote};if(!response.ok||!result.quote)throw new Error('quote');setQuote(result.quote);setState('ready')}catch(error){if((error as Error).name!=='AbortError'){setQuote(null);setState('error')}}},250);return()=>{clearTimeout(timer);controller.abort()}},[months,quantity,countryCode,offer])
  const country=countries.find(item=>item.code===countryCode)??countries[0]??FALLBACK_COUNTRIES[0],copies=months*(Number(quantity)||1),dispatchDate=formatLongDate(firstEditionDate()),savings=quote?quote.durationDiscountMinor+quote.offerDiscountMinor:0
  const checkoutHref=`/checkout/razorpay?duration=${months}&quantity=${Number(quantity)||1}&country=${country.code}${quote?.promotion?`&code=${encodeURIComponent(offer.trim())}`:''}`
  return <section id="plans" className="border-b border-graphite bg-paper scroll-mt-24">
    <Reveal className={`${SHELL} pt-4 pb-14 md:pb-20 lg:pb-24`}>
      <h2 className="sr-only">Choose your subscription plan</h2>
      <div className="grid items-start gap-8 lg:grid-cols-[1.15fr_0.85fr]">
        <div className="rounded-2xl border border-graphite bg-paper-raised p-6 shadow-[6px_6px_0_rgba(23,21,18,0.12)] md:p-8">
          <fieldset className="m-0 border-0 p-0"><legend className="font-display text-xl font-bold">Choose a duration</legend><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{DURATIONS.map(value=><label key={value} className={`cursor-pointer rounded-xl border p-4 text-center ${months===value?'border-2 border-graphite bg-sun':'border-graphite bg-paper'}`}><input data-analytics-duration={value} className="sr-only" type="radio" name="duration" checked={months===value} onChange={()=>setMonths(value)}/><span className="block font-display text-lg font-bold">{value} {value===1?'month':'months'}</span><span className="mt-1 block font-mono text-[9.5px] uppercase">{quote&&months===value?(quote.durationDiscountMinor?`${Math.round(quote.durationDiscountMinor/quote.subtotalMinor*100)}% term saving`:'Base price'):'Select'}</span></label>)}</div></fieldset>
          <div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="font-mono text-[11px] uppercase">Copies per edition<span className="mt-2 flex items-center overflow-hidden rounded-xl border border-graphite bg-paper"><button type="button" aria-label="Decrease copies" disabled={(Number(quantity)||1)<=1} onClick={()=>setQuantity(Math.max(1,(Number(quantity)||1)-1))} className="px-4 py-3 text-xl disabled:opacity-30">-</button><input type="number" min={1} value={quantity} onChange={event=>setQuantity(event.target.value===''?'':Math.max(1,Math.floor(Number(event.target.value))||1))} aria-label="Copies per edition" onBlur={()=>{if(!quantity)setQuantity(1)}} className="min-w-0 w-full bg-paper px-2 py-3 text-center font-sans text-[15px] outline-none"/><button type="button" aria-label="Increase copies" onClick={()=>setQuantity((Number(quantity)||1)+1)} className="px-4 py-3 text-xl">+</button></span></label><label className="font-mono text-[11px] uppercase">Delivery country<select value={countryCode} onChange={event=>setCountryCode(event.target.value)} className="mt-2 block w-full rounded-xl border border-graphite bg-paper px-4 py-3 font-sans text-[15px]">{countries.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label></div>
          <label className="mt-5 block font-mono text-[11px] uppercase">Promotion code<input value={offer} onChange={event=>setOffer(event.target.value)} placeholder="Optional" className="mt-2 block w-full rounded-xl border border-graphite bg-paper px-4 py-3 font-sans text-[15px] normal-case"/>{offer&&state==='ready'&&<span className={`mt-2 block text-[10px] ${quote?.promotion?'text-teal-deep':'text-founder-deep'}`}>{quote?.promotion?'Eligible promotion applied.':'This code is not eligible for the selection.'}</span>}</label>
          <div className="mt-7 border-t border-rule pt-5 text-sm leading-relaxed text-graphite-soft"><p><strong className="text-graphite">{copies} printed copies</strong> across {months} monthly editions.</p><p className="mt-2">First eligible edition dispatches around <strong className="text-graphite">{dispatchDate}</strong>; allow {country.transit} after dispatch.</p><p className="mt-2">Payment covers the full selected term. Your subscription renews automatically every {months} {months===1?'month':'months'} for the same quantity until cancelled. Cancel before the renewal date to prevent the next charge.</p></div>
        </div>
        <aside aria-live="polite" className="rounded-2xl border-2 border-graphite bg-sun p-6 shadow-[8px_8px_0_rgba(23,21,18,0.18)] lg:sticky lg:top-28 md:p-8"><p className={`${EYEBROW} text-graphite`}>Your order</p><h3 className="font-display text-2xl font-bold">{months} {months===1?'month':'months'}</h3>{state==='loading'&&<p className="mt-6">Calculating current price…</p>}{state==='error'&&<p role="alert" className="mt-6">Pricing is temporarily unavailable. Please retry.</p>}{quote&&state==='ready'&&<><p className="mt-3 text-sm">Base price: {money(quote.monthlyPriceMinor,quote.currency)} per copy/month</p><dl className="mt-6 flex flex-col gap-3 border-y border-graphite py-5 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{money(quote.subtotalMinor,quote.currency)}</dd></div><div className="flex justify-between text-teal-deep"><dt>Term discount</dt><dd>−{money(quote.durationDiscountMinor,quote.currency)}</dd></div><div className="flex justify-between text-teal-deep"><dt>Promotion</dt><dd>−{money(quote.offerDiscountMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Delivery</dt><dd>{money(quote.shippingMinor,quote.currency)}</dd></div><div className="flex justify-between"><dt>Tax ({quote.taxBasisPoints/100}%)</dt><dd>{money(quote.taxMinor,quote.currency)}</dd></div></dl><div className="mt-5 flex items-end justify-between"><span className="font-mono text-[10px] uppercase">Total payable</span><strong className="font-display text-3xl">{money(quote.totalMinor,quote.currency)}</strong></div><p className="mt-2 text-right font-mono text-[10px]">Exact saving: {money(savings,quote.currency)}</p><a href={checkoutHref} className={`mt-6 block text-center ${CTA}`}>Continue to checkout</a></>}<nav aria-label="Purchase policies" className="mt-5 flex flex-wrap justify-center gap-3 font-mono text-[9.5px] uppercase"><a href="/policies/refund">Cancellation &amp; refunds</a><a href="/policies/delivery">Delivery</a><a href="/policies/privacy">Privacy</a><a href="/policies/subscription">Subscription terms</a></nav></aside>
      </div>
    </Reveal>
    <div className="subscription-mobile-summary sticky bottom-0 z-40 border-t border-graphite bg-paper-raised p-3 shadow-[0_-4px_0_rgba(23,21,18,0.08)] lg:hidden"><div className="mx-auto flex max-w-[680px] items-center justify-between gap-3"><div><span className="block font-mono text-[9px] uppercase">{copies} copies · total payable</span><strong className="font-display text-xl">{quote&&state==='ready'?money(quote.totalMinor,quote.currency):'Calculating…'}</strong></div>{quote&&state==='ready'&&<a href={checkoutHref} className={CTA}>Checkout</a>}</div></div>
  </section>
}
