/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as ApiAnalyticsRouteImport } from './routes/api.analytics'
import { Route as ApiCustomerRouteImport } from './routes/api.customer'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiLogoutRouteImport } from './routes/api.logout'
import { Route as ApiPricingRouteImport } from './routes/api.pricing'
import { Route as ApiReadinessRouteImport } from './routes/api.readiness'
import { Route as ApiSessionRouteImport } from './routes/api.session'
import { Route as CheckoutRazorpayRouteImport } from './routes/checkout.razorpay'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as ApiAdminDispatchRouteImport } from './routes/api.admin.dispatch'
import { Route as ApiAdminFilesRouteImport } from './routes/api.admin.files'
import { Route as ApiAssetsIdRouteImport } from './routes/api.assets.$id'
import { Route as ApiCustomerFilesRouteImport } from './routes/api.customer.files'
import { Route as ApiRazorpayCheckoutRouteImport } from './routes/api.razorpay.checkout'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api.webhooks.razorpay'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth.$provider.callback'
import { Route as AuthProviderStartRouteImport } from './routes/auth.$provider.start'
import { Route as ApiAdminFileIdRouteImport } from './routes/api.admin.file.$id'
import { Route as ApiCustomerFileIdRouteImport } from './routes/api.customer.file.$id'
import { Route as ApiCustomerInvoicePaymentIdRouteImport } from './routes/api.customer.invoice.$paymentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerRoute = ApiCustomerRouteImport.update({
  id: '/api/customer',
  path: '/api/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricingRoute = ApiPricingRouteImport.update({
  id: '/api/pricing',
  path: '/api/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadinessRoute = ApiReadinessRouteImport.update({
  id: '/api/readiness',
  path: '/api/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRazorpayRoute = CheckoutRazorpayRouteImport.update({
  id: '/checkout/razorpay',
  path: '/checkout/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDispatchRoute = ApiAdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => ApiAdminRoute,
} as any)
const ApiAdminFilesRoute = ApiAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ApiAdminRoute,
} as any)
const ApiAssetsIdRoute = ApiAssetsIdRouteImport.update({
  id: '/api/assets/$id',
  path: '/api/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerFilesRoute = ApiCustomerFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ApiCustomerRoute,
} as any)
const ApiRazorpayCheckoutRoute = ApiRazorpayCheckoutRouteImport.update({
  id: '/api/razorpay/checkout',
  path: '/api/razorpay/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderStartRoute = AuthProviderStartRouteImport.update({
  id: '/auth/$provider/start',
  path: '/auth/$provider/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFileIdRoute = ApiAdminFileIdRouteImport.update({
  id: '/file/$id',
  path: '/file/$id',
  getParentRoute: () => ApiAdminRoute,
} as any)
const ApiCustomerFileIdRoute = ApiCustomerFileIdRouteImport.update({
  id: '/file/$id',
  path: '/file/$id',
  getParentRoute: () => ApiCustomerRoute,
} as any)
const ApiCustomerInvoicePaymentIdRoute =
  ApiCustomerInvoicePaymentIdRouteImport.update({
    id: '/invoice/$paymentId',
    path: '/invoice/$paymentId',
    getParentRoute: () => ApiCustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order-complete': typeof OrderCompleteRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/customer': typeof ApiCustomerRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/pricing': typeof ApiPricingRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/api/session': typeof ApiSessionRoute
  '/checkout/razorpay': typeof CheckoutRazorpayRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/api/admin/dispatch': typeof ApiAdminDispatchRoute
  '/api/admin/files': typeof ApiAdminFilesRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/customer/files': typeof ApiCustomerFilesRoute
  '/api/razorpay/checkout': typeof ApiRazorpayCheckoutRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/auth/$provider/start': typeof AuthProviderStartRoute
  '/api/admin/file/$id': typeof ApiAdminFileIdRoute
  '/api/customer/file/$id': typeof ApiCustomerFileIdRoute
  '/api/customer/invoice/$paymentId': typeof ApiCustomerInvoicePaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order-complete': typeof OrderCompleteRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/customer': typeof ApiCustomerRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/pricing': typeof ApiPricingRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/api/session': typeof ApiSessionRoute
  '/checkout/razorpay': typeof CheckoutRazorpayRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/api/admin/dispatch': typeof ApiAdminDispatchRoute
  '/api/admin/files': typeof ApiAdminFilesRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/customer/files': typeof ApiCustomerFilesRoute
  '/api/razorpay/checkout': typeof ApiRazorpayCheckoutRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/auth/$provider/start': typeof AuthProviderStartRoute
  '/api/admin/file/$id': typeof ApiAdminFileIdRoute
  '/api/customer/file/$id': typeof ApiCustomerFileIdRoute
  '/api/customer/invoice/$paymentId': typeof ApiCustomerInvoicePaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order-complete': typeof OrderCompleteRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/customer': typeof ApiCustomerRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/pricing': typeof ApiPricingRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/api/session': typeof ApiSessionRoute
  '/checkout/razorpay': typeof CheckoutRazorpayRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/api/admin/dispatch': typeof ApiAdminDispatchRoute
  '/api/admin/files': typeof ApiAdminFilesRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/customer/files': typeof ApiCustomerFilesRoute
  '/api/razorpay/checkout': typeof ApiRazorpayCheckoutRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/auth/$provider/start': typeof AuthProviderStartRoute
  '/api/admin/file/$id': typeof ApiAdminFileIdRoute
  '/api/customer/file/$id': typeof ApiCustomerFileIdRoute
  '/api/customer/invoice/$paymentId': typeof ApiCustomerInvoicePaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/login'
    | '/order-complete'
    | '/register'
    | '/subscription'
    | '/api/admin'
    | '/api/analytics'
    | '/api/customer'
    | '/api/health'
    | '/api/logout'
    | '/api/pricing'
    | '/api/readiness'
    | '/api/session'
    | '/checkout/razorpay'
    | '/policies/$slug'
    | '/api/admin/dispatch'
    | '/api/admin/files'
    | '/api/assets/$id'
    | '/api/customer/files'
    | '/api/razorpay/checkout'
    | '/api/webhooks/razorpay'
    | '/auth/$provider/callback'
    | '/auth/$provider/start'
    | '/api/admin/file/$id'
    | '/api/customer/file/$id'
    | '/api/customer/invoice/$paymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/login'
    | '/order-complete'
    | '/register'
    | '/subscription'
    | '/api/admin'
    | '/api/analytics'
    | '/api/customer'
    | '/api/health'
    | '/api/logout'
    | '/api/pricing'
    | '/api/readiness'
    | '/api/session'
    | '/checkout/razorpay'
    | '/policies/$slug'
    | '/api/admin/dispatch'
    | '/api/admin/files'
    | '/api/assets/$id'
    | '/api/customer/files'
    | '/api/razorpay/checkout'
    | '/api/webhooks/razorpay'
    | '/auth/$provider/callback'
    | '/auth/$provider/start'
    | '/api/admin/file/$id'
    | '/api/customer/file/$id'
    | '/api/customer/invoice/$paymentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/login'
    | '/order-complete'
    | '/register'
    | '/subscription'
    | '/api/admin'
    | '/api/analytics'
    | '/api/customer'
    | '/api/health'
    | '/api/logout'
    | '/api/pricing'
    | '/api/readiness'
    | '/api/session'
    | '/checkout/razorpay'
    | '/policies/$slug'
    | '/api/admin/dispatch'
    | '/api/admin/files'
    | '/api/assets/$id'
    | '/api/customer/files'
    | '/api/razorpay/checkout'
    | '/api/webhooks/razorpay'
    | '/auth/$provider/callback'
    | '/auth/$provider/start'
    | '/api/admin/file/$id'
    | '/api/customer/file/$id'
    | '/api/customer/invoice/$paymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  RegisterRoute: typeof RegisterRoute
  SubscriptionRoute: typeof SubscriptionRoute
  ApiAdminRoute: typeof ApiAdminRouteWithChildren
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiCustomerRoute: typeof ApiCustomerRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiPricingRoute: typeof ApiPricingRoute
  ApiReadinessRoute: typeof ApiReadinessRoute
  ApiSessionRoute: typeof ApiSessionRoute
  CheckoutRazorpayRoute: typeof CheckoutRazorpayRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
  ApiRazorpayCheckoutRoute: typeof ApiRazorpayCheckoutRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
  AuthProviderStartRoute: typeof AuthProviderStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer': {
      id: '/api/customer'
      path: '/api/customer'
      fullPath: '/api/customer'
      preLoaderRoute: typeof ApiCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pricing': {
      id: '/api/pricing'
      path: '/api/pricing'
      fullPath: '/api/pricing'
      preLoaderRoute: typeof ApiPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readiness': {
      id: '/api/readiness'
      path: '/api/readiness'
      fullPath: '/api/readiness'
      preLoaderRoute: typeof ApiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/razorpay': {
      id: '/checkout/razorpay'
      path: '/checkout/razorpay'
      fullPath: '/checkout/razorpay'
      preLoaderRoute: typeof CheckoutRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dispatch': {
      id: '/api/admin/dispatch'
      path: '/dispatch'
      fullPath: '/api/admin/dispatch'
      preLoaderRoute: typeof ApiAdminDispatchRouteImport
      parentRoute: typeof ApiAdminRoute
    }
    '/api/admin/files': {
      id: '/api/admin/files'
      path: '/files'
      fullPath: '/api/admin/files'
      preLoaderRoute: typeof ApiAdminFilesRouteImport
      parentRoute: typeof ApiAdminRoute
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/api/assets/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/files': {
      id: '/api/customer/files'
      path: '/files'
      fullPath: '/api/customer/files'
      preLoaderRoute: typeof ApiCustomerFilesRouteImport
      parentRoute: typeof ApiCustomerRoute
    }
    '/api/razorpay/checkout': {
      id: '/api/razorpay/checkout'
      path: '/api/razorpay/checkout'
      fullPath: '/api/razorpay/checkout'
      preLoaderRoute: typeof ApiRazorpayCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider/start': {
      id: '/auth/$provider/start'
      path: '/auth/$provider/start'
      fullPath: '/auth/$provider/start'
      preLoaderRoute: typeof AuthProviderStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/file/$id': {
      id: '/api/admin/file/$id'
      path: '/file/$id'
      fullPath: '/api/admin/file/$id'
      preLoaderRoute: typeof ApiAdminFileIdRouteImport
      parentRoute: typeof ApiAdminRoute
    }
    '/api/customer/file/$id': {
      id: '/api/customer/file/$id'
      path: '/file/$id'
      fullPath: '/api/customer/file/$id'
      preLoaderRoute: typeof ApiCustomerFileIdRouteImport
      parentRoute: typeof ApiCustomerRoute
    }
    '/api/customer/invoice/$paymentId': {
      id: '/api/customer/invoice/$paymentId'
      path: '/invoice/$paymentId'
      fullPath: '/api/customer/invoice/$paymentId'
      preLoaderRoute: typeof ApiCustomerInvoicePaymentIdRouteImport
      parentRoute: typeof ApiCustomerRoute
    }
  }
}

interface ApiAdminRouteChildren {
  ApiAdminDispatchRoute: typeof ApiAdminDispatchRoute
  ApiAdminFilesRoute: typeof ApiAdminFilesRoute
  ApiAdminFileIdRoute: typeof ApiAdminFileIdRoute
}

const ApiAdminRouteChildren: ApiAdminRouteChildren = {
  ApiAdminDispatchRoute: ApiAdminDispatchRoute,
  ApiAdminFilesRoute: ApiAdminFilesRoute,
  ApiAdminFileIdRoute: ApiAdminFileIdRoute,
}

const ApiAdminRouteWithChildren = ApiAdminRoute._addFileChildren(
  ApiAdminRouteChildren,
)

interface ApiCustomerRouteChildren {
  ApiCustomerFilesRoute: typeof ApiCustomerFilesRoute
  ApiCustomerFileIdRoute: typeof ApiCustomerFileIdRoute
  ApiCustomerInvoicePaymentIdRoute: typeof ApiCustomerInvoicePaymentIdRoute
}

const ApiCustomerRouteChildren: ApiCustomerRouteChildren = {
  ApiCustomerFilesRoute: ApiCustomerFilesRoute,
  ApiCustomerFileIdRoute: ApiCustomerFileIdRoute,
  ApiCustomerInvoicePaymentIdRoute: ApiCustomerInvoicePaymentIdRoute,
}

const ApiCustomerRouteWithChildren = ApiCustomerRoute._addFileChildren(
  ApiCustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  RegisterRoute: RegisterRoute,
  SubscriptionRoute: SubscriptionRoute,
  ApiAdminRoute: ApiAdminRouteWithChildren,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiCustomerRoute: ApiCustomerRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiPricingRoute: ApiPricingRoute,
  ApiReadinessRoute: ApiReadinessRoute,
  ApiSessionRoute: ApiSessionRoute,
  CheckoutRazorpayRoute: CheckoutRazorpayRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ApiAssetsIdRoute: ApiAssetsIdRoute,
  ApiRazorpayCheckoutRoute: ApiRazorpayCheckoutRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
  AuthProviderStartRoute: AuthProviderStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
